:sparkles: Add feedback form #5
ashawe/CTF-Website-Template-2020 pull request #7
Opened 2020-10-21 06:03 UTC by jcombs0929

2020-10-21 15:29 UTC, ashawe commented on feedback.html
> +                                <label for="interface">Interface</label>
Change to: How was the User Interface?
Options: 
- Easy to understand
- Just Right
- Difficult to navigate through.

2020-10-21 15:31 UTC, ashawe commented on feedback.html
> +                                <label for="organizers">Who were the organizers?</label>
The question wasn't who were the organizers xD
It is supposed to be: How supportive were the organizers?
Options:
Very supportive
Just right
Not at all

2020-10-21 15:32 UTC, ashawe commented on feedback.html
> +                                <label for="maintainers">Maintainers?</label>
Same as organizers

2020-10-21 15:32 UTC, ashawe commented on feedback.html
> +                                <label for="maintainers">Maintainers?</label>
Same as organizers

2020-10-21 15:32 UTC, ashawe commented on feedback.html
> +                                <label for="additionComments">Any additional comments or questions?</label>
also ask about any difficulties faced

2020-10-21 15:33 UTC, ashawe requested changes
Add these things:
How would you rate the questions?
- easy to solve
- just right
- difficult to solve
- difficult to decipher the question

How would you rate the clues / hints?
- easy to understand
- made the questions too easy
- just right
- did not help

2020-10-21 15:35 UTC, ashawe commented on feedback.html
> +                                <label for="additionComments">Any additional comments or questions?</label>
in the same question

2020-10-21 16:27 UTC, jcombs0929 commented
@ashawe Can you clarify what you mean here?

> On Oct 21, 2020, at 10:36 AM, Harsh Saglani <notifications@github.com> wrote:
> 
> 
> @ashawe commented on this pull request.
> 
> In feedback.html <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509391680>:
> 
> > +                            <div class="col-md-12">
> +                                <label for="overallExperience">How would you rate your overall experience?</label>
> +                                <select class="custom-select d-block w-100" id="overallExperience">
> +                                    <option value="">Select Overall Experience</option>
> +                                    <option>Excellent</option>
> +                                    <option>Average</option>
> +                                    <option>Poor</option>
> +                                    <option>N/A</option>
> +                                </select>
> +                                <div class="invalid-feedback">Please choose a rating</div>
> +                            </div>
> +                    
> +                        </div>
> +                        <div class="row mb-3">
> +                            <div class="col-md-12 mb-3">
> +                                <label for="additionComments">Any additional comments or questions?</label>
> in the same question
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509391680>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGAWIHLHNYQFD4WZMK56VFLSL35WBANCNFSM4SZJMD7A>.
>

2020-10-21 16:28 UTC, jcombs0929 commented
@ashawe Did you want a separate textarea for difficulties faced, did you want it added to Additional Comments question?

> On Oct 21, 2020, at 10:33 AM, Harsh Saglani <notifications@github.com> wrote:
> 
> 
> @ashawe commented on this pull request.
> 
> In feedback.html <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509389147>:
> 
> > +                                </div>
> +                                <div class="invalid-feedback">Please select Yes/No</div>
> +                            </div>
> +                        </div>
> +
> +                        <div class="row mb-4">
> +                            <div class="col-md-12">
> +                                <label for="organizers">Who were the organizers?</label>
> +                                <input type="text" class="form-control" id="organizers" placeholder="Add Organizers">
> +                            </div>
> +                            <div class="invalid-feedback">Invalid</div>
> +                        </div>
> +
> +                        <div class="row mb-4">
> +                            <div class="col-md-12">
> +                                <label for="maintainers">Maintainers?</label>
> Same as organizers
> 
> In feedback.html <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509389467>:
> 
> > +                            <div class="col-md-12">
> +                                <label for="overallExperience">How would you rate your overall experience?</label>
> +                                <select class="custom-select d-block w-100" id="overallExperience">
> +                                    <option value="">Select Overall Experience</option>
> +                                    <option>Excellent</option>
> +                                    <option>Average</option>
> +                                    <option>Poor</option>
> +                                    <option>N/A</option>
> +                                </select>
> +                                <div class="invalid-feedback">Please choose a rating</div>
> +                            </div>
> +                    
> +                        </div>
> +                        <div class="row mb-3">
> +                            <div class="col-md-12 mb-3">
> +                                <label for="additionComments">Any additional comments or questions?</label>
> also ask about any difficulties faced
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#pullrequestreview-513820446>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGAWIHL7XWIRWRWHX3IABLLSL35LFANCNFSM4SZJMD7A>.
>

2020-10-21 17:05 UTC, ashawe commented
> 
> @ashawe Did you want a separate textarea for difficulties faced, did you want it added to Additional Comments question?

nope in the same

2020-10-21 17:26 UTC, jcombs0929 commented
@ashawe Sorry, can you clarify what you mean here?
> > +                            <div class="col-md-12">
> +                                <label for="overallExperience">How would you rate your overall experience?</label>
> +                                <select class="custom-select d-block w-100" id="overallExperience">
> +                                    <option value="">Select Overall Experience</option>
> +                                    <option>Excellent</option>
> +                                    <option>Average</option>
> +                                    <option>Poor</option>
> +                                    <option>N/A</option>
> +                                </select>
> +                                <div class="invalid-feedback">Please choose a rating</div>
> +                            </div>
> +                    
> +                        </div>
> +                        <div class="row mb-3">
> +                            <div class="col-md-12 mb-3">
> +                                <label for="additionComments">Any additional comments or questions?</label>
> in the same question
> 

> On Oct 21, 2020, at 10:36 AM, Harsh Saglani <notifications@github.com> wrote:
> 
> 
> @ashawe commented on this pull request.
> 
> In feedback.html <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509391680>:
> 
> > +                            <div class="col-md-12">
> +                                <label for="overallExperience">How would you rate your overall experience?</label>
> +                                <select class="custom-select d-block w-100" id="overallExperience">
> +                                    <option value="">Select Overall Experience</option>
> +                                    <option>Excellent</option>
> +                                    <option>Average</option>
> +                                    <option>Poor</option>
> +                                    <option>N/A</option>
> +                                </select>
> +                                <div class="invalid-feedback">Please choose a rating</div>
> +                            </div>
> +                    
> +                        </div>
> +                        <div class="row mb-3">
> +                            <div class="col-md-12 mb-3">
> +                                <label for="additionComments">Any additional comments or questions?</label>
> in the same question
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/ashawe/CTF-Website-Template-2020/pull/7#discussion_r509391680>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGAWIHLHNYQFD4WZMK56VFLSL35WBANCNFSM4SZJMD7A>.
>

2020-10-22 04:58 UTC, ashawe commented
@jcombs0929 change the question from 
Any additional comments or questions?
to
Did you face any difficulties? or have additional comments or questions?

2020-10-22 05:08 UTC, jcombs0929 commented
@ashawe I have committed my changes based on your feedback. Let me know if you have any other edits.

2020-10-22 07:18 UTC, ashawe approved these changes

2020-10-22 07:19 UTC, merged